feat: Adds CI implementation
looker-open-source/viz-spider-marketplace pull request #17
Opened 2024-01-30 15:48 UTC by andres-rubio-go

2024-02-01 20:44 UTC, jeremytchang commented on webpack.config.js
> +    filename: "spider.js",
`filename: "bundle.js"`

2024-02-01 20:59 UTC, jeremytchang requested changes

2024-02-01 20:59 UTC, jeremytchang commented on webpack.config.js
> +    filename: "spider.js",
`filename: "bundle.js"`

2024-02-01 21:02 UTC, jeremytchang requested changes
Copying the requirements here:

Based off this[ example PR](https://github.com/looker-open-source/viz-radial_gauge-marketplace/pull/24): 
- Copy the .github/workflows directory with its 2 yaml files.
- For README, outside of initial unique info per viz, the rest should be exact copy.
- Update webpack config to output the js bundle to `dist\bundle.js`. This must result from `yarn build` call to ensure release workflow works. Looks like some of the webpack configs are inconsistent, so we’ll need to be careful here and ensure locally the output is correct.
- Remove any minified bundle js files.
- Update gitignore to ignore dist directory
- Make sure the master branch is called `master` for release and ci workflow to work.

2024-02-08 16:23 UTC, yesudeep approved these changes

2024-02-22 17:04 UTC, yesudeep commented on .github/workflows/ci-build.yml
> +    uses: looker-open-source/reusable-actions/.github/workflows/marketplace-viz-ci-build.yml@main
Please add a blank line at the end of this file.

2024-02-22 17:04 UTC, yesudeep commented on .github/workflows/release.yml
> +    secrets: inherit
Please add a blank line at the end of this file.

2024-03-18 21:39 UTC, jeremytchang approved these changes

2024-03-18 21:59 UTC, merged